package guepardoapps.guepardobirthday.common;

public class Bundles {
	public static final String NOTIFICATION_BUNDLE = "NOTIFICATION_BUNDLE";
	public static final String BIRTHDAY_DETAIL_BUNDLE_TYPE_ID = "BIRTHDAY_DETAIL_BUNDLE_TYPE_ID";
	public static final String BIRTHDAY_DETAIL_BUNDLE_TYPE_NAME = "BIRTHDAY_DETAIL_BUNDLE_TYPE_NAME";
	public static final String BIRTHDAY_DETAIL_BUNDLE_TYPE_DAY = "BIRTHDAY_DETAIL_BUNDLE_TYPE_DAY";
	public static final String BIRTHDAY_DETAIL_BUNDLE_TYPE_MONTH = "BIRTHDAY_DETAIL_BUNDLE_TYPE_MONTH";
	public static final String BIRTHDAY_DETAIL_BUNDLE_TYPE_YEAR = "BIRTHDAY_DETAIL_BUNDLE_TYPE_YEAR";
}